/** Fields that must never appear in logs (passwords, tokens, cookies). */
export const REDACT_PATHS = [
  "password",
  "token",
  "authorization",
  "cookie",
  "code",
  "otp",
  "AUTH_SECRET",
  "sessionToken",
  "*.password",
  "*.token",
  "*.authorization",
  "*.cookie",
  "*.code",
  "*.otp",
  "*.sessionToken",
  "*.AUTH_SECRET",
  "req.headers.authorization",
  "req.headers.cookie",
  "headers.authorization",
  "headers.cookie",
  "headers[\"x-solviax-session\"]",
  "err.config.headers.Authorization",
] as const;
